package com.iot.services;

import com.iot.models.dto.MetricResponseDto;
import com.iot.models.entities.MetricEntity;
import com.iot.models.enums.MetricType;
import com.iot.repositories.MetricRepository;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Business logic for persisting and retrieving computed metrics.
 *
 * <p>Metrics are never created by external clients — they are generated internally
 * by {@link ProcessingService} after running algorithms over telemetry data.
 * Returns {@link MetricResponseDto} only — never JPA entities.
 */
@Service
public class MetricService {

    private final MetricRepository metricRepository;

    public MetricService(MetricRepository metricRepository) {
        this.metricRepository = metricRepository;
    }

    /**
     * Persists a computed metric generated by an algorithm.
     * Called internally by ProcessingService — not exposed directly to external clients.
     */
    @Transactional
    public MetricResponseDto save(MetricType type, Double value, String unit) {
        MetricEntity entity = MetricEntity.builder()
                .type(type)
                .value(value)
                .unit(unit)
                .build();

        MetricEntity saved = metricRepository.save(entity);
        return MetricResponseDto.fromEntity(saved);
    }

    /**
     * Returns all metrics ordered by most recent first.
     * Used for full historical consultation in the frontend.
     */
    @Transactional(readOnly = true)
    public List<MetricResponseDto> findAll() {
        return metricRepository.findAll(Sort.by(Sort.Direction.DESC, "createdAt"))
                .stream()
                .map(MetricResponseDto::fromEntity)
                .toList();
    }

    /**
     * Returns all metrics of a given type ordered by most recent first.
     * Used to display a specific algorithm's history in the frontend.
     */
    @Transactional(readOnly = true)
    public List<MetricResponseDto> findByType(MetricType type) {
        return metricRepository.findByTypeOrderByCreatedAtDesc(type)
                .stream()
                .map(MetricResponseDto::fromEntity)
                .toList();
    }

    /**
     * Returns the most recent metric of a given type.
     * Used for live display of the latest algorithm output in the frontend.
     */
    @Transactional(readOnly = true)
    public Optional<MetricResponseDto> findLatestByType(MetricType type) {
        return metricRepository.findTopByTypeOrderByCreatedAtDesc(type)
                .map(MetricResponseDto::fromEntity);
    }
}