services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=soft_eng_db'
      - 'POSTGRES_PASSWORD=dev_password_2026'
      - 'POSTGRES_USER=soft_eng_user'
    ports:
      - '5432:5432'
 