package com.iot.models.entities;
import com.iot.models.enums.EventType;

import jakarta.persistence.Column;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

import org.hibernate.annotations.CreationTimestamp;

/**
 * JPA entity mapped to the {@code events} table.
 *
 * <p>Fields: {@code id} (generated), {@code deviceId}, {@code type},
 * {@code createdAt} (set on insert via {@link CreationTimestamp}).
 *
 * <p>Never return this type from REST controllers — use {@link com.iot.models.dto.EventResponseDto}.
 */
@Entity
@Table(name = "events")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EventEntity {

    //Unique identifier generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    //Type of event reported by the ESP32.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 64)
    private EventType type;

    //Timestamp automatically generated when the event is stored.
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant timestamp;

}